### ISSUE TITLE
Documentation or code needs updating: process "deploy-production" fails

### ISSUE THREAD

**Issue by Indre87** [MAD-I-T/magento-actions#22]
Documentation states that accepted values in action.yml are:

`Possible values: build, static-test, integration-test, unit-test, phpcs-test, deploy-staging, deploy-production, cleanup-staging, cleanup-production, security-scan-[files|modules]`

When using "deploy-production" the main.yml it fails to "file not found", because the script is named "deploy-prod.sh". Using "deploy-prod" everything works fine. 

So the documentation could be updated or the filename changed accordingly.

**Comment by seyuf** [comment]
Indeed my bad, we wanted to replace production by prod, for simplicity, but then for the same reason, wee decided to put it back as production sound more pro. And to keep backward compatibility going, we planned to keep both :).
So what happen here is that i just forgot to put it back  :slightly_smiling_face: . Many thanks to you for pointing this out :pray:
