### ISSUE TITLE
Add support for PHP 8.1

### ISSUE THREAD

**Issue by Mr-Leonerrr** [MAD-I-T/magento-actions#33]
The new versions of Magento use PHP 8.1, the input should be updated

**Comment by seyuf** [comment]
Hi,
 it already does. 
The php version is automatically match to the magento version according to [here](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html). If noting is specified.
Proof [Here](https://github.com/seyuf/magento-actions-sample/actions/runs/3282877183/jobs/5406868613#step:10:25).
And this has been the case for a long time now. So maybe you're using an older version of the action?

**Comment by seyuf** [comment]
![php8 1-support](https://user-images.githubusercontent.com/3765910/198352493-a7333058-b1ac-4528-a3b6-b0e58fca8e3e.png)

**Comment by Mr-Leonerrr** [comment]
Cool, thanks for clarifying!
