### ISSUE TITLE
`rm: cannot remove 'magento-phpstan': No such file or directory`

### ISSUE THREAD

**Issue by stevenou** [MAD-I-T/magento-actions#49]
Hello,

I followed this template: https://github.com/MAD-I-T/magento-worldline-sips2/blob/master/.github/workflows/main.yml

At the end of the `phpstan` step, it exits with error:
`rm: cannot remove 'magento-phpstan': No such file or directory`

I took a look at https://github.com/MAD-I-T/magento-actions/blob/master/scripts/phpstan.sh (which I believe is what executes for that step), and I noticed that there is `cd "$PROJECT_PATH/magento-phpstan"` towards the beginning of the file.

My guess is that the script needs to `cd` out of that directory before being able to execute the `rm` function? 

Either way, would appreciate any thoughts on this issue. 

Thanks!

**Comment by seyuf** [comment]
Hi sir,

you're absolutely right, i just deploy a partial fix for this. 
I have to test and handle cases when the script fails before the rm. But you should be good to go on @v3.20 of the action.

Regards

**Comment by stevenou** [comment]
Wow, thanks for such fast resolution! Can confirm it is working correctly now.
