### ISSUE TITLE
Elasticsearch/Opensearch not working?

### ISSUE THREAD

**Issue by stevenou** [MAD-I-T/magento-actions#50]
Hello, when attempting to run unit tests (following this template: https://github.com/MAD-I-T/magento-worldline-sips2/blob/master/.github/workflows/main.yml), I am receiving the following error message:

```
In SearchConfig.php line 81:

  Could not validate a connection to the OpenSearch. No alive nodes found in   
  your cluster
```

I'm not sure if this is related to https://github.com/MAD-I-T/magento-actions/issues/35? I would imagine that it should still be able to work using the `elasticsearch` docker image, but the error message specifically refers to `OpenSearch` instead of `ElasticSearch`, so I'm not sure. 

Your thoughts are appreciated. 

Thanks!

**Comment by seyuf** [comment]
You 're probably trying to use elasticsearch with an opensearch alias in the services section? In which case you need to remove  `elasticsearch: 1` from the action/step.

**Comment by seyuf** [comment]
You're config [here](https://github.com/InvisibleCommerce/shipped-suite-magento-module/blob/main/.github/workflows/checks.yml#L42) should be good to go.

**Comment by stevenou** [comment]
I believe I have the correct config as you suggested? https://github.com/InvisibleCommerce/shipped-suite-magento-module/pull/3/files

**Comment by seyuf** [comment]
Yep, this will work fine. 
You can also use opensearch since magento 2.4.6. I just updated https://github.com/MAD-I-T/magento-worldline-sips2/blob/master/.github/workflows/main.yml in that sense.
Also, as mentioned above, starting v3.20 elasticsearch/opensearch services will be automatically detected if not specified.
You can thus then remove `elasticsearch: 1` from the different actions.

**Comment by stevenou** [comment]
Ah, thanks.

Removing `elasticsearch: 1` seems to do the trick (seems somewhat counter-intuitive, since the service is still `elasticsearch`). On the other hand, switching the service to `opensearch` also works.

**Comment by seyuf** [comment]
Yep, there must be a bug somewhere. Let's keep this open.
