### ISSUE TITLE
Custom unit test config path (unit_test_config) not working(v3.24)

### ISSUE THREAD

**Issue by aneel11** [MAD-I-T/magento-actions#56]
Hi

I have set custom unit test config path ( **unit_test_config: 'magento/phpunit.xml** ). I have added this phpunit.xml file in magento folder where magento root files exist. But it is not taking that phpunit.xml file. Can you suggest how we can do that, following is my main.xml file:

name: m2-actions-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    name: 'm2 tests & build'
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://elasticsearch:7.17.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    #- uses: actions/checkout@v3

    - name: 'install fresh magento repo'
      if: always()
      #if: ${{false}}
      uses: MAD-I-T/magento-actions@v3.24
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'create-project'
        magento_version: 2.4.5
        no_push: 1

    - name: 'launch magento2 unit test'
      if: always()
      uses: MAD-I-T/magento-actions@v3.24
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'unit-test'
        override_settings: true
        unit_test_config: 'magento/phpunit.xml'

**Comment by seyuf** [comment]
Hi there,

Two potential causes:
1. Try with just 'phpunit.xml' whitout the magento ? As the script is run from the magento dir in the repo
2. you're overriding the settings, meaning if you have a custom **scripts/unit-test.sh** . That script will take over the default action script.

Lets check the these two scenarios ? First ?

Best

**Comment by aneel11** [comment]
Hi

I have tested by add only phpunit.xml in main.yml and with overriding_setting true and false as well but it is giving only one error "**Could not read "phpunit.xml"**." each time.

Additional, if I add **no_push=0** in install magento then it takes **phpunit.xml** but it pushes code to my repo which I don't want to push it.

**Comment by seyuf** [comment]
Humm also your use case is not clear. What do you have exactly in your github repo?
Where you're phpunit.xml comes from?

**Comment by aneel11** [comment]
Hi

I have created the same structure as you defined above:

`├── .github
│   └── workflows # directory where the workflows are found, see below for an example of main.yml 
├── magento # with you magento src
└── magento/phpunit.xml`

And same main.xml code:
`
    steps:

    - name: 'launch magento2 unit test'
      if: always()
      uses: MAD-I-T/magento-actions@v3.24
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        process: 'unit-test'
        override_settings: 1
        unit_test_config: 'phpunit.xml'
`

But this time its giving following error:
![image](https://github.com/MAD-I-T/magento-actions/assets/24469855/82efbdde-b385-44de-9895-4efcb1d931ad)

And it is also not taking my custom script file unit-test.sh.

**Comment by aneel11** [comment]
This is my repo : https://github.com/aneel2023/magento24

And this is the last failed pipeline: https://github.com/aneel2023/magento24/actions/runs/6009275299/job/16298381812

Basically, I want to execute unit tests only on app/code folder that's why I want to set custom path when uni test job execute but it is not taking my phpunit.xml file from magento folder, you can check. I tried almost all ways whatever you defined in your documentation.

**Comment by seyuf** [comment]
I didn't notice yesterday in your main.yml. But of course if you comment the checkout (i.e `    #- uses: actions/checkout@v3`), your files will not be downloaded from github... Please uncomment, that was the issue all along.

Side note: if you're using magento 2.4.5 its best to use opensearch in place of elasticsearch.

**Comment by aneel11** [comment]
Thank you very much above works and saved my time. I am closing this issue.
