### ISSUE TITLE
Upgraded to Composer 2

### ISSUE THREAD

**Issue by deedy-tech** [MAD-I-T/magento-actions#6]
Has Composer been upgraded to version 2 on the docker image? 

When I try and do a deploy or build it now fails with 

"You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2."

The use of Composer 2 forces an upgrade to Magento 2.4.2.

**Comment by seyuf** [comment]
@deedy-tech crap, indeed it seems a new build was lauched 4 days ago? On **dockerhub**? I don't get it. I didn't touch the Dockerfile ... Thanks for the heads up.

**Comment by seyuf** [comment]
@deedy-tech can you try again? I just downgraded composer to 1.

**Comment by deedy-tech** [comment]
@seyuf yeah it's working again. Thanks for sorting.
